### ISSUE TITLE
How to make this work with ranger?

### ISSUE THREAD

**Issue by thepenguinthatwants** [salman-abedin/devour#11]
How to make this behave when opening with ranger or terminal? For now when I open them they open in separate windowses.
I am using i3wm with st terminal.

I got it work with my gui file manager by editing entries in /usr/share/applications/ and using bash aliases eased a bit. But how to get this work with ranger?

I edited rifle.conf like this 
```
mime ^video,       has mpv,      X, flag f = devour mpv --fs -- "$@"
mime ^video,       has mpv,      X, flag f = devour  mpv -- "$@"
```
but  it doesnt seem to trigger devour it. Any tips?

**Comment by salman-abedin** [comment]
I don't have any experience with using ranger or rifle but I'm sure that the scripting shouldn't be any different than how you are launching from the shell. Hopefully you'll figure it out if you already haven't. =)
