### ISSUE TITLE
devour error with filenames that include parentheses

### ISSUE THREAD

**Issue by rusty-electron** [salman-abedin/devour#16]
Hi, @salman-abedin sorry to bother you again but devour has the same issue I previously had, this time it is with filenames that have parentheses in them.

![image](https://user-images.githubusercontent.com/22986666/93029123-83e96780-f636-11ea-83e1-925f45ac7ef8.png)

`mpvd` is an alias for `devour mpv`

_Originally posted by @rusty-electron in https://github.com/salman-abedin/devour/issues/13#issuecomment-691728123_

**Comment by salman-abedin** [comment]
Nah it's fine. Unfortunately, I am a little caught up these days but I'll take care of it soon.

**Comment by rusty-electron** [comment]
no prob, take your time :+1:

**Comment by antaxiom** [comment]
I just wanna add this also happens with `'` as well for me

**Comment by KenJean** [comment]
As a temporary workaround I find that symlink-ing the target file to a generic name works. i.e.

`ln -nsf <target file with problematic name> /tmp/dummy`
`devour <application> /tmp/dummy`

It's gets tricky if you are invoking *devour* from within another shell script, but it can be handled with some command-line-fu.

**Comment by salman-abedin** [comment]
Upgrade to version 12 guys.
