### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by MarcinWieczorek** [salman-abedin/devour#2]
Hello, thank you for the tool.

I copied and reduced sudo's zsh autocompletion, I thought I'd share. I would do a pull request, but I don't really understand how it works. Hope you merge it some day.

```
#compdef devour

setopt localoptions extended_glob

local environ e cmd
local -a args
local -a _comp_priv_prefix

zstyle -a ":completion:${curcontext}:" environ environ

for e in "${environ[@]}"
do local -x "$e"
done

args+=(
  '(-)1:command: _command_names -e'
  '*::arguments:{ _comp_priv_prefix=( $cmd -n ${(kv)opt_args[(I)(-[ugHEP]|--(user|group|set-home|preserve-env|preserve-groups))]} ) ; _normal }'
)

_arguments -s -S $args
```

**Comment by salman-abedin** [comment]
I seek to keep my scripts portable and turning it into a shell specific script would defeat that purpose. 
Glad to know you got some use out of it though.

**Comment by MarcinWieczorek** [comment]
Autocompletion is an addition to the script, it tunes the shell to the tool and not the other way. It's your choice though.

**Comment by AriaMoradi** [comment]
`complete -cf devour` would be much simpler but you need to add it to your .bashrc
