### ISSUE TITLE
Remove surrounding $() to avoid executing output

### ISSUE THREAD

**Issue by guardam** [salman-abedin/devour#4]
`$("$@") > /dev/null 2>&1`

Should be replaced with:

`("$@" >/dev/null 2>&1)`

See [SC2091](https://github.com/koalaman/shellcheck/wiki/SC2091) for more informations.

**Comment by salman-abedin** [comment]
I knew I was doing something fishy there!
Couldn't put my fingers on it.
Thanks for pointing it out.
Adding you as a contributor.
