### ISSUE TITLE
Doesn't play nice with Crystal

### ISSUE THREAD

**Issue by diogox** [salman-abedin/devour#6]
This should probably be an issue on your `Crystal` repo.

But when `Crystal` toggles `solo` mode, it picks up already hidden windows. Meaning, when you navigate, it shows the devoured window, which I don't think is the desired effect for either scripts.

**Comment by salman-abedin** [comment]
I am aware of this issue and I would have already fixed it if I hadn't moved on to a different workflow other than [Crystal](https://github.com/salman-abedin/crystal). Tell you what though, I will get right on it asap. =)

**Comment by diogox** [comment]
Fantastic! Thank you :smile: 

Out of curiosity, mind sharing what you're using in place of Crystal? :thinking:

**Comment by salman-abedin** [comment]
Well, I've just moved on to a **tmux** workflow where I no longer need more than a single terminal.
So **Crystal** has become kinda obsolete for me.
I do use the fullscreen mode at times when I need a distraction free environment.
