### ISSUE TITLE
devouring everything

### ISSUE THREAD

**Issue by roof98** [salman-abedin/devour#7]
Manjaro KDE and Pop OS gnome3
using devour on mpv swallows my entire screen and all windows. I open the logout menu and that will get swallowed too. Any window I open will immediately get swallowed. 

What I am typing:

devour mpv /path/to/vid 
works totally fine, but if I use a bash alias 
alias mpv='devour mpv'
and then devour mpv /path/to/vid then all windows get swallowed. 

If I open gimp from terminal then it works fine with 
devour gimp
but if I launch gimp from an alias of 
alias gimp='devour gimp'

So there seems to be a problem when it comes to launching from a bash alias. I can replicate the problem with any program so long as I do it from an alias. Manually typing devour [program name] works everytime, but goes wrong every time from an alias

I was using devour fine until today when I installed it again with the new code changes and the problems began as described.

**Comment by salman-abedin** [comment]
Note that you are using **gimp** and **mpv** as aliases which are system commands themselves.
This is considered a bad practice in general and now you know why. I would suggest using unique aliases, not just for using devour but as a rule of thumb.
If the issue still persists, let me know.

**Comment by roof98** [comment]
ok, I will try that once I have access to that PC. Thanks!
2 quick comments:

1: these aliases, bad form though they may be, were working fine prior to the update on 7/7-8. It made sense to me to use the alias as a 1:1 replacement for the command itself since devour is taking the place of a window swallowing function, which itself does not need to be explicitly called to work.

2: The DT video linked on the readme page shows him making aliases the same as how I did them, so this may be a problem for more people in the future if they make aliases the same DT did in the video.

**Comment by salman-abedin** [comment]
That is because after I added the shell alias support due to user demands, the arguments are now being run in an interactive shell.

In any case, I'm gonna reopen the issue and leave it hanging for people to take note.

I appreciate you pointing it out btw. =)

**Comment by roof98** [comment]
no problem man. Github is kinda new to me so I hope I did everything right. 

Really like what you are doing dude.
