### ISSUE TITLE
Running devour creates a new zsh session

### ISSUE THREAD

**Issue by ghost** [salman-abedin/devour#9]
When I run devour, a new zsh instance is started.
By itself this isn't much of a problem, but when running devour in lf, it exits and outputs.
zsh: suspended (tty output)  lf
This also happens in bash.
The terminal emulator that im using is alacritty.
Thanks!

**Comment by salman-abedin** [comment]
Its due to the shell alias feature I had to integrate due to people's demand.
Apparently, it has not been playing well and frankly, I am no longer maintaining the project.
In any case, I will take a look into it and let you know what's up.

**Comment by ghost** [comment]
Alright, thanks for the response.

**Comment by salman-abedin** [comment]
Kindly check the new commit. Should be fine now.
